import pandas as pd


# Load the Mila Institute hebrew words dataset
stopwords_df = pd.read_excel(r'Mila - Stopwords.xlsx')

# Define the types of words we wand to delete from the texts and pass them to a list
delete_lst = ['conjunction',
              'preposition',
              'negation',
              'pronoun',
              'copula',
              'existential',
              'interrogative',
              'numeral',
              'quantifier']

stopwords_lst = stopwords_df['Undotted'][stopwords_df['POS'].isin(delete_lst)].tolist()
verb_lst = stopwords_df['Undotted'][stopwords_df['POS'].isin(['verb', 'participle:verb'])].tolist()

# Add more words to the stopwords_lst manually
stopwords_manually = ['אני',
                      'כל',
                      'רק',
                      'מה',
                      'לא',
                      'היא',
                      'אנחנו',
                      'זה',
                      'היום',
                      'ולא',
                      'בכל',
                      'עוד',
                      'אתמול',
                      'שלא',
                      'ולכן',
                      'rt',
                      'gt',
                      'כבר',
                      'שוב',
                      'יום',
                      'בן',
                      'הרבה',
                      'בן',
                      'שלי',
                      'שלו',
                      'מאוד',
                      'כעת',
                      'הם',
                      'הזה',
                      'עכשיו',
                      'לי',
                      'לנו',
                      'שלך',
                      'אז',
                      'כאן',
                      'להיות',
                      'אתה',
                      'לכל',
                      'הבוקר',
                      'כך',
                      'את',
                      'בלתי',
                      'באופן',
                      'השבוע',
                      'the',
                      'to',
                      'of',
                      'is',
                      'in',
                      'i',
                      'a',
                      'day',
                      'today',
                      'and',
                      'you',
                      'this',
                      'an',
                      'הערב',
                      'וגם',
                      'הזו',
                      'אפשר',
                      'שאני',
                      'שהוא',
                      'א',
                      'אמר',
                      'אומר',
                      'היו',
                      'שיש',
                      'וזה',
                      'ה',
                      'אותה',
                      'אותי',
                      'מחר',
                      'דבר',
                      'שזה',
                      'שנה',
                      'שם',
                      'ש',
                      'מ',
                      'בו',
                      'ברור',
                      'עדיין',
                      'בו',
                      'להם',
                      'לה',
                      'הזאת',
                      'שהם',
                      'תהיה',
                      'שלנו',
                      'אי',
                      'שלה',
                      'הייתי',
                      'כרגע',
                      'ו',
                      'פעם',
                      'כזה',
                      'ככה',
                      'היתה',
                      'אנשים',
                      'לכם',
                      'אותם',
                      'ביום',
                      'הכל',
                      'לך',
                      'יכול',
                      'אתם',
                      'הייתה',
                      'עושה',
                      'ממש',
                      'ואני',
                      'פי',
                      'איש',
                      'רגע',
                      'מקום',
                      'אולי',
                      'יכול',
                      'פה',
                      'הלילה',
                      'הכי',
                      'שלהם',
                      'שאתה',
                      'הו',
                      'בוקר',
                      'רבה',
                      'שלכם',
                      'מאז',
                      'למי',
                      'gtgt',
                      'שבו',
                      'ידי',
                      'לישראל',
                      'בישראל']

stopwords_lst = stopwords_lst + stopwords_manually

