import pandas as pd


# Load the Mila Institute hebrew words dataset
stopwords_df = pd.read_excel(r'Mila - Stopwords.xlsx')

# Define the types of words we wand to delete from the texts and pass them to a list
delete_lst = ['conjunction',
              'preposition',
              'negation',
              'pronoun',
              'copula',
              'existential',
              'interrogative',
              'numeral',
              'quantifier']

stopwords_lst = stopwords_df['Undotted'][stopwords_df['POS'].isin(delete_lst)].tolist()

# Add more words to the stopwords_lst manually
stopwords_manually = ['אני',
                      'כל',
                      'רק',
                      'מה',
                      'לא',
                      'היא',
                      'אנחנו',
                      'זה',
                      'היום',
                      'ולא',
                      'בכל',
                      'עוד',
                      'אתמול',
                      'שלא',
                      'ולכן',
                      'rt',
                      'כבר',
                      'שוב',
                      'יום',
                      'בן',
                      'הרבה',
                      'בן',
                      'שלי',
                      'שלו',
                      'מאוד',
                      'כעת',
                      'הם',
                      'הזה',
                      'עכשיו',
                      'לי',
                      'לנו',
                      'שלך',
                      'אז',
                      'כאן',
                      'להיות',
                      'אתה',
                      'לכל',
                      'הבוקר',
                      'כך',
                      'את',
                      'בלתי',
                      'באופן',
                      'השבוע',
                      'the',
                      'to',
                      'of',
                      'is',
                      'in',
                      'i',
                      'a',
                      'day',
                      'today',
                      'and',
                      'you',
                      'this',
                      'הערב',
                      'וגם',
                      'הזו',
                      'אפשר',
                      'שאני',
                      'שהוא',
                      'א',
                      'אמר',
                      'אומר',
                      'היו',
                      'שיש',
                      'וזה',
                      'ה',
                      'אותה',
                      'אותי',
                      'מחר',
                      'דבר',
                      'שזה',
                      'שנה',
                      'שם']

stopwords_lst = stopwords_lst + stopwords_manually

